### ISSUE TITLE
Cross-browser testing - Windows Edge: TODO Before Release

### ISSUE THREAD

**Issue by jonsanders101** [MarcelCutts/pride-london-web-gatsby#106]
Per this issue: https://github.com/MarcelCutts/pride-london-web-gatsby/issues/91

**Comment by ds300** [comment]
# Main Events listing page
- [ ] Looks correct (designs over here: https://zpl.io/VQqjOxR )
- [ ] All filters seem to work ok
- [ ] Clearing the filters works
- [ ] show more button works
- [ ] show more button is not visible when there are no more events to show
- [ ] clicking the 'back to main site' button takes you back to prideinlondon.org
- [ ] clicking the 'donate' button takes you to donate.prideinlondon.org
- [ ] clicking an event takes you to the event detail page
# Event detail page
- [ ] Looks correct (designs over here: https://zpl.io/V4JWEN0 )
- [ ] Map is showing
- [ ] Clicking the map takes you to the right location in google maps
- [ ] 'You may also like' section contains relevant entries (should respect the filters or category of current event)
- [ ] clicking `view all events` takes you back to the events listing page
- [ ] clicking the 'back to main site' button takes you back to prideinlondon.org
- [ ] clicking the 'donate' button takes you to donate.prideinlondon.org
- [ ] clicking the pride logo takes you back to the events listing page
